name: set-env-example
on: watch

jobs:
  build:

    if: github.actor == 'francisfuzz'
    
    runs-on: ubuntu-latest

    steps:

    - name: Set `color` as an environment variable
      run: echo "::set-env name=color::yellow"

    - name: Echo the value of `color` 
      run: echo $color
 
    - name: Set `NOW` as an environment variable
      run: |
        # This style of environment variable assignment will only be scoped within this step.
        LOCAL_NOW=`date`
        
        # In order to let the next step read `NOW`, we need to use the `set-env` workflow command.
        # https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
        echo "::set-env name=NOW::$LOCAL_NOW"
    
    - name: Echo the value of `NOW`
      run: echo $NOW
